### ISSUE TITLE
Identify iSpindel from homepage

### ISSUE THREAD

**Issue by andrewreid** [mp-se/gravitymon-ui#6]
I have multiple iSpindels and I choose to name them by the colour of their lid (ispindel-COLOUR). They could have any arbitrary name, but there's no easy way of telling which unit I'm looking at in the UI, unless I go into `DeviceSettingsView` and identify the mDNS name in the settings.

I considered a couple of options - adding it in parentheses on the homepage next to the IP address; alternatively, replacing the word "Home" with `status.mdns` might make it easily apparent.

I'd offer a pull request, but wanted to discuss it first.

**Comment by mp-se** [comment]
Good suggestion, I have also have several devices so I have a similar problem...  I like the idea of having it visible at any page so either the menu bar or status bar would be a good option (or the tab name in the browser). If you want to try out a few options you can do that. 

If you build gravitymon with the ENABLE_REMOTE_UI_DEVELOPMENT define then you can work towards the device directly or use the mock server included in the project. Let me know if you have issues with it and I can explain it in more detail. 

A pull request is always welcome.

**Comment by mp-se** [comment]
I had a look at bootstrap and how they use the navbar in their examples and this could be a way forward. 
![image](https://github.com/user-attachments/assets/590a491a-f2b5-49b7-aae5-ca227321f57c)

Adding software name to the left and the device name to the right. This could be done in the menubar.vue component quite easy. 

I can share the proposed changes if you want to contribute to the project.

**Comment by andrewreid** [comment]
That looks really good! The only other approach I thought of was having a configurable color for the menu bar, however that seems like a lot more work to implement for the same result. I guess the only benefit might be that the identity of the unit might be easier to determine from a small screen device like a phone. Not sure if the juice is worth the squeeze, though.

I'm very happy to do some work, otherwise if you've got it ready to go I'm not precious about you commiting the code either 😄

**Comment by mp-se** [comment]
You are right, changing color would be more work since I base the design on the standard bootstrap color scheme, so that means that one needs to customize bootstrap. It could be done using javascript but since bootstrap does not yet support vue there is a conflict when trying to use the javascript interface with bootstrap so the vue code stops working...  There is a vue/bs5 project in the works but that is still very early in the development so this could be a future option. 

I will push the change I have done to the project and make a new build.

**Comment by mp-se** [comment]
Added to main
